### PR TITLE
chromium-vaapi: 75.0.3770.80-1

### PR DESCRIPTION
**Pull request by michaellass**
Tested basic functionality and video acceleration on an Intel HD 4000.

### CODE REVIEW

**Comment by maximbaz** [comment]
Thank you so much!

**Comment by maximbaz** [comment]
I have just tested, unfortunately for me the playback on YouTube is not starting anymore, tried both H264 and VP9, both iHD and i965 drivers. Still works when downgrading to v64 😞 Any ideas what might be wrong?

Will post this on AUR as well, maybe someone will have an idea.

**Comment by michaellass** [comment]
Unfortunately I have no clue. My hardware is quite old, so I can only test with libva-intel-driver and H264. I will test with your binary package later. Although there should be no difference to my own build.

**Comment by michaellass** [comment]
No issues with your binary package here. So maybe it's hardware dependent.

**Pull request merged**
